### PR TITLE
[KOGITO-6602] Setup Eventing Kogito CI to integrate with OLM integrat…

### PR DESCRIPTION
**Pull request by davidesalerno**
…ion test

# Changes

- CI: added support to execute olm tests

/kind ci

**Release Note**

```release-note
Added olm-tests goal to make file to execute the OML checks 
```

**Docs**

```docs
To execute the OLM checks execute: make olm-tests
```

### CODE REVIEW

**Comment by ricardozanini** [comment]
@davidesalerno are we good?

**Comment by davidesalerno** [comment]
@ricardozanini I think tha now we are good and we can merge

**Review by ricardozanini — APPROVED** [review]

**Pull request merged**
