### PR TITLE
[KOGITO-6532] Enable OLM installation bundle

### PR DESCRIPTION
**Pull request by ricardozanini**
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

# Changes

- 🎁 Adds OLM bundle to enable installation on OLM enabled clusters

/kind enhancement

See https://issues.redhat.com/browse/KOGITO-6532

**Release Note**

```release-note
KogitoSource can now be installed on [OLM based clusters](https://olm.operatorframework.io/)
```

TODO:

- ~update README to add the alternative way of installing the source~ as soon as the source is published in the hub
- [x] test the examples we have available with the OLM installation
- ~Integrate CI with OLM testing~ in another PR: https://issues.redhat.com/browse/KOGITO-6602

### CODE REVIEW

**Comment by ricardozanini** [comment]
I've removed the admission webhooks from the installation since OLM and Knative won't play together. See https://github.com/operator-framework/operator-lifecycle-manager/issues/2577 for reference.

**Comment by sutaakar** [comment]
/lgtm
Operator is properly installed and integrated:
image

**Pull request merged**
